language: node_js
node_js:
  - "stable"
before_script:
  - cd functions && npm install
script:
  - echo "Stated deployment..."
  - echo "Installing dependencies..."
  - yarn
  - echo "Building project..."
  - yarn build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
